config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/sign_in', to: 'sessions#new', as: 'sign_in'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy', as: 'sign_out'

  get '/users/:id/edit_preferences', to: 'users#edit_preferences', as: 'edit_preferences'
  patch '/users/:id/update_preferences', to: 'users#update_preferences', as: 'update_preferences'

  resources :users
  # resources :account_activations, only: [:edit]
  resources :categories, only: [:show]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :activation_token
  # before_create :create_activation_digest
  has_secure_password
  has_and_belongs_to_many :categories
  belongs_to :schedule

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true
  validates :email, format: /\w+@\w+\.\w+/, :on => :create
  validates :password, presence: true, confirmation: true

  scope :everyday, -> { where(:schedule_id => Schedule.everyday) }
  scope :weekend, -> { where(:schedule_id => Schedule.weekend) }
  scope :week, -> { where(:schedule_id => Schedule.week) }
  scope :two_weeks, -> { where(:schedule_id => Schedule.two_weeks) }
  scope :month, -> { where(:schedule_id => Schedule.month) }

  # def self.new_token
  #   SecureRandom.urlsafe_base64
  # end
  #
  # def self.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                 BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end

  # def create_activation_digest
  #   self.activation_token = User.new_token
  #   self.activation_digest = User.digest(activation_token)
  # end

  # def authenticated?(attribute, token)
  #   digest = send("#{attribute}_digest")
  #   return false if digest.nil?
  #   BCrypt::Password.new(digest).is_password?(token)
  # end
end

app/views/shared/_edit_form.html.erb
<div class='form-horizontal'>
  <%= form_for @user do |f| %>
    <div class='form-group'>
      <%= f.label :username, class: 'col-md-3 control-label' %>
      <div class='col-md-9'>
        <%= f.text_field :username, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <%= f.label :email, class: 'col-md-3 control-label' %>
      <div class='col-md-9'>
        <%= f.email_field :email, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <%= f.label :password, class: 'col-md-3 control-label' %>
      <div class='col-md-9'>
        <%= f.password_field :password, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation, class: 'col-md-3 control-label' %>
      <div class='col-md-9'>
        <%= f.password_field :password_confirmation, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <div class='col-md-offset-3 col-md-9'>
        <div class="modal-footer">
          <%= f.submit 'Save Changes', class: 'btn btn-default' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_edit_preferences_form.html.erb
<% if session[:user_id] %>
  <%= form_tag({id: @user.id, controller: 'users', action: 'update_preferences'}, method: 'patch') do |f| %>
    <div class='form'>
      <h5>Categories</h5>
      <fieldset>
        <% @categories.each do |category| %>
          <div class='col-md-4'>
            <% unless @user.categories.include?(category) %>
              <div class='form group'>
                <%= check_box_tag 'user[category_ids][]', category.id %>
                <%= label_tag :name, "#{category.name}" %>
              </div>
            <% else %>
              <div class='form group'>
                <%= check_box_tag 'user[category_ids][]', category.id, checked = true %>
                <%= label_tag :name, "#{category.name}" %>
              </div>
            <% end %>
          </div>
        <% end %>
      </fieldset>
    </div>
    <div class='form'>
      <h5>Schedules</h5>
      <fieldset>
        <% @schedules.each do |schedule| %>
          <% unless @user.schedule_id == schedule.id %>
            <div class='form group'>
              <%= radio_button_tag :schedule_id, "#{schedule.id}"%>
              <%= label_tag :schedule_id, "#{schedule.name}" %>
              <small><%= " #{schedule.description}" %></small>
            </div>
          <% else %>
            <div class='form group'>
              <%= radio_button_tag :schedule_id, "#{schedule.id}", checked = true %>
              <%= label_tag :schedule_id, "#{schedule.name}" %>
              <small><%= " #{schedule.description}" %></small>
            </div>
          <% end %>
        <% end %>
      </fieldset>
    </div>
    <div class='modal-footer'>
      <%= submit_tag 'Update Preferences', class: 'btn btn-default' %>
    </div>
  <% end %>
<% end %>

app/views/shared/_event_modal.html.erb
<% @category.events.todays_events.each do |event| %>
  <li><a href='#' data-toggle='modal' data-target="#modal-<%= event.id %>"><%= event.title %></a></li>
  <div id="modal-<%= event.id %>" class='modal fade'>
    <div class='modal-dialog'>
      <div class='modal-content'>
        <div class='modal-header'>
          <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
          <h4 class='modal-title'><%= event.title %></h4>
        </div>
        <div class='modal-body'>
          <p><%= pretty_date(event.date) %></p>
          <p><%= event.description %></p>
          <p><%= event.location %></p>
          <p><%= event.email %></p>
          <p><%= link_to 'More Info', event.url, :target => '_blank' %></p>
        </div>
        <div class='modal-footer'>
          <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-default'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button class='navbar-toggle' type='button' data-toggle='collapse' data-target='.js-navbar-collapse'>
  			<span class='sr-only'>Toggle navigation</span>
  			<span class='icon-bar'></span>
  			<span class='icon-bar'></span>
  			<span class='icon-bar'></span>
      </button>
      <%= link_to 'My Seattle Events', root_path, class: 'navbar-brand' %>
    </div>
    <div class='collapse navbar-collapse js-navbar-collapse'>
      <ul class='nav navbar-nav navbar-left'>
        <li><%= link_to 'Home', root_path %></li>
        <li class='dropdown megamenu'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Categories <span class='caret'></span></a>
            <div class='mega dropdown-menu'>
              <ul class='list-unstyled col-lg-3 col-sm-6' role='menu'>
                <% @categories[0..7].each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category.id) %></li>
                <% end %>
              </ul>
              <ul class='list-unstyled col-lg-3 col-sm-6' role='menu'>
                <% @categories[8..15].each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category.id) %></li>
                <% end %>
              </ul>
              <ul class='list-unstyled col-lg-3 col-sm-6' role='menu'>
                <% @categories[16..23].each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category.id) %></li>
                <% end %>
              </ul>
              <ul class='list-unstyled col-lg-3 col-sm-6' role='menu'>
                <% @categories[24..28].each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category.id) %></li>
                <% end %>
              </ul>
            </div>
        </li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if session[:user_id].nil? %>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown'><b>Sign Up </b><span class='caret'></span></a>
            <ul class='sign-dp dropdown-menu'>
              <li>
                <div class='row'>
                  <div class='col-md-12'>
                    <div class='form'>
                      <%= form_for @user do |f| %>
                        <div class='form-group'>
                          <%= f.label :username %>
                          <%= f.text_field :username, required: true %>
                        </div>
                        <div class='form-group'>
                          <%= f.label :email, 'Email Address' %>
                          <%= f.email_field :email, required: true %>
                        </div>
                        <div class='form-group'>
                          <%= f.label :password %>
                          <%= f.password_field :password, required: true %>
                        </div>
                        <div class='form-group'>
                          <%= f.label :password_confirmation %>
                          <%= f.password_field :password_confirmation, required: true %>
                        </div>
                        <div class='form-group'>
                          <%= f.submit 'Sign Up', class: 'btn btn-default btn-block' %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </li>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown'><b>Sign In </b><span class='caret'></span></a>
            <ul class='sign-dp dropdown-menu'>
              <li>
                <div class='row'>
                  <div class='col-md-12'>
                    <div class='form'>
                      <%= form_for(:session, url: sign_in_path)  do |f| %>
                        <div class='form-group'>
                          <%= f.label :username %>
                          <%= f.text_field :username, :required => true %>
                        </div>
                        <div class='form-group'>
                          <%= f.label :password %>
                          <%= f.password_field :password, :required => true %>
                        </div>
                        <div class='form-group'>
                          <%= f.submit 'Sign In', class: 'btn btn-default btn-block' %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </li>
        <% else %>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown'><b><%= @user.username %> </b><span class='caret'></span></a>
            <ul class='sign-dp dropdown-menu'>
              <li class='user'><a href='#' data-toggle='modal' data-target='#edit-user'>Edit Profile</a></li>
              <li class='user'><a href='#' data-toggle='modal' data-target='#edit-pref'>Newsletter Preferences</a></li>
            </ul>
          </li>
          <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- Modals triggered from a nav bar must be placed outside of the nav element in order to work -->
<div id='edit-user' class='modal fade'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
        <h4 class='modal-title'>Edit Profile</h4>
      </div>
      <div class='modal-body'>
        <%= render partial: 'shared/edit_form' %>
      </div>
    </div>
  </div>
</div>

<div id='edit-pref' class='modal fade'>
  <div class='modal-dialog edit'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
        <h4 class='modal-title edit-pref'>Newsletter Preferences</h4>
      </div>
      <div class='modal-body edit-pref'>
        <%= render partial: 'shared/edit_preferences_form' %>
      </div>
    </div>
  </div>
</div>